groups:
  blue: 0.5
  red: 0.2
  green: 0.2

empty: 0.1

shape:
  - 50
  - 50

is_costs: False

is_smart: False

max_iters: 50

similar_list:
  - 0.2
  - 0.2
  - 0.2

resources_list:
  - 200
  - 200
  - 200

adaptivities_list:
  - 0
  - 0
  - 0