groups:
  blue: 0.3
  red: 0.3
  green: 0.3

empty: 0.1

shape:
  - 50
  - 50

is_costs: False

is_smart: False

max_iters: 50

similar_list:
  - 0.4
  - 0.4
  - 0.4

resources_list:
  - 200
  - 200
  - 200

adaptivities_list:
  - 0
  - 0
  - 0
