groups:
  blue: 0.25
  red: 0.25
  green: 0.25

empty: 0.25

shape:
  - 50
  - 50

similar_list:
  - 0.5
  - 0.5
  - 0.5

resources_list:
  - 200
  - 200
  - 200

adaptivities_list:
  - 0.001
  - 0.001
  - 0.001
