groups:
  blue: 0.225
  red: 0.225
  green: 0.225
  yellow: 0.225

empty: 0.1

shape:
  - 50
  - 50

is_costs: False

is_smart: False

max_iters: 50

similar_list:
  - 0.3
  - 0.3
  - 0.3
  - 0.3

resources_list:
  - 200
  - 200
  - 200
  - 200

adaptivities_list:
  - 0
  - 0
  - 0
  - 0
