groups:
  blue: 0.45
  red: 0.45

empty: 0.1

is_costs: False

is_smart: False

max_iters: 100

shape:
  - 50
  - 50

similar_list:
  - 0.4
  - 0.4

resources_list:
  - 200
  - 200

adaptivities_list:
  - 0
  - 0
